import {Router} from 'express';
import {apiRateLimit,handelError,employeeValidation} from '../middleware';
import clinicController from '../controller/clinic';
const clinicRoutes=Router();
clinicRoutes.get('/seo-url-availability-check',[apiRateLimit(5,20)],handelError(clinicController.checkClinicSeourlAvailability));
clinicRoutes.get('/mobile-unique-check',[apiRateLimit(5,20)],handelError(clinicController.checkClinicMobileUnique));
clinicRoutes.get('/username-unique-check',[apiRateLimit(5,20)],handelError(clinicController.checkClinicloginUserNameUnique));
clinicRoutes.post('/add-new-clinic',[apiRateLimit(1,4),employeeValidation(1)],handelError(clinicController.addNewClinic));
clinicRoutes.get('/clinic-list',[apiRateLimit(1,4)],handelError(clinicController.getClinicList));
clinicRoutes.get('/get-doctors-list',[apiRateLimit(1,4)],handelError(clinicController.getDoctorsList));
clinicRoutes.get('/doctor-complete-details',[apiRateLimit(1,3)],handelError(clinicController.doctorCompleteDetails));
clinicRoutes.post('/approve-doctor',[apiRateLimit(1,3),employeeValidation(1)],handelError(clinicController.approveDoctor));
clinicRoutes.post('/change-doctor-active-status',[apiRateLimit(1,3),employeeValidation(1)],handelError(clinicController.changeDoctorActiveStatus));
clinicRoutes.get('/clinic-banners',[apiRateLimit(1,3)],handelError(clinicController.clinicBanners));
clinicRoutes.get('/clinic-specialization',[apiRateLimit(1,3)],handelError(clinicController.clinicSpecializations));
export default clinicRoutes;
