import {Router} from 'express';
import {apiRateLimit,handelError,employeeValidation} from '../middleware';
import enquiryController from '../controller/enquiry';
const routes=Router();
routes.get('/get-enquiry-list',[apiRateLimit(30,30)],handelError(enquiryController.enquiryList));
routes.post('/update-enquiry-status',[apiRateLimit(1,2),employeeValidation(1)],handelError(enquiryController.updateEnquiryStatus));
routes.get('/get-dynamic-form-submissions-list',[apiRateLimit(1,1)],handelError(enquiryController.getDynamicFormSubmissionsList));
routes.get('/get-prime-enquiries-list',[apiRateLimit(30,30)],handelError(enquiryController.primeEnquiriesList));
routes.post('/update-prime-enquiry',[apiRateLimit(1,2),employeeValidation(1)],handelError(enquiryController.updatePrimeEnquiry));
routes.post('/cancel-prime-enquiry',[apiRateLimit(1,2),employeeValidation(1)],handelError(enquiryController.cancelPrimeEnquiry));
routes.get('/prime-enquiry-watchers',[apiRateLimit(30,30)],handelError(enquiryController.getPrimeEnquiryWatchers));
routes.post('/prime-enquiry-watchers',[apiRateLimit(10,30),employeeValidation(1)],handelError(enquiryController.addPrimeEnquiryWatcher));
routes.post('/delete-prime-enquiry-watcher',[apiRateLimit(10,30),employeeValidation(1)],handelError(enquiryController.deletePrimeEnquiryWatcher));
export default routes;