import {Router} from 'express';
import {apiRateLimit,handelError} from '../middleware';
import AppointmentController from '../controller/appointment';
import pageVisiterController from '../controller/page-visiter';
import reportController from '../controller/report';
const reportRouter = Router();
reportRouter.get("/business-listing-summary",[apiRateLimit(10,10)],handelError(reportController.businessListingSummary));
reportRouter.get('/todays-booked-appointment-doctors', [apiRateLimit(10, 30)], handelError(AppointmentController.getTodaysAppointmentBookedDoctors));
reportRouter.get('/patients-doctor-list', [apiRateLimit(10, 30)], handelError(AppointmentController.getTodaysPatientsDoctorList));
reportRouter.get('/appointments-dashboard', [apiRateLimit(10, 30)], handelError(AppointmentController.getAppointmentsDashboard));
reportRouter.get("/page-visit-graph-data",[apiRateLimit(10,10)],handelError(pageVisiterController.getPageVisitReport));
reportRouter.get("/site-visiters",[apiRateLimit(10,10)],handelError(pageVisiterController.getPageVisiters));
reportRouter.get("/site-traffic-dashboard",[apiRateLimit(10,30)],handelError(pageVisiterController.getSiteTrafficDashboard));
reportRouter.get("/clinic-traffic",[apiRateLimit(10,30)],handelError(pageVisiterController.getClinicTraffic));
reportRouter.get("/generate-clinic-daily-report",[apiRateLimit(10,10)],handelError(reportController.generateClinicDailyReport));
reportRouter.get("/generate-doctors-rating-review-report",[apiRateLimit(10,10)],handelError(reportController.generateRatingReviewReport));
export default reportRouter;