import { Router } from "express";
import {apiRateLimit,handelError,parseFormData,employeeValidation} from '../middleware';
import manageTaskController from "../controller/manage-task";
const tasksRouter=Router();
tasksRouter.post("/create",[apiRateLimit(1,2),employeeValidation(1)],handelError(manageTaskController.createTask));
tasksRouter.get("/list",[apiRateLimit(5,10),employeeValidation(1)],handelError(manageTaskController.tasksList));
tasksRouter.get("/detail",[apiRateLimit(10,10),employeeValidation(1)],handelError(manageTaskController.taskDetail));
tasksRouter.get("/employee-list",[apiRateLimit(5,10),employeeValidation(1)],handelError(manageTaskController.employeeList));
tasksRouter.post("/assign-employee",[apiRateLimit(2,5),employeeValidation(1)],handelError(manageTaskController.assignEmployeeToTask));
tasksRouter.post("/add-comment",[apiRateLimit(2,5),employeeValidation(1)],handelError(manageTaskController.addCommentToTask));
tasksRouter.post("/change-status",[apiRateLimit(2,5),employeeValidation(1)],handelError(manageTaskController.changeTaskStatus));
tasksRouter.post("/change-task-title",[apiRateLimit(2,5),employeeValidation(1)],handelError(manageTaskController.changeTaskTitle));
tasksRouter.post("/change-description",[apiRateLimit(2,5),employeeValidation(1)],handelError(manageTaskController.changeTaskDescription));
tasksRouter.post("/change-reporter",[apiRateLimit(2,5),employeeValidation(1)],handelError(manageTaskController.changeReporterOfTask));
tasksRouter.post("/change-priority",[apiRateLimit(2,5),employeeValidation(1)],handelError(manageTaskController.changePriorityOfTask));
tasksRouter.post("/delete",[apiRateLimit(1,2),employeeValidation(1)],handelError(manageTaskController.deleteTask));
tasksRouter.post("/submit-rating",[apiRateLimit(2,5),employeeValidation(1)],handelError(manageTaskController.submitRating));
tasksRouter.get("/reminders/all",[apiRateLimit(5,10),employeeValidation(1)],handelError(manageTaskController.getAllReminders));
tasksRouter.post("/reminders/create",[apiRateLimit(2,5),employeeValidation(1)],handelError(manageTaskController.createReminder));
tasksRouter.post("/reminders/delete",[apiRateLimit(1,2),employeeValidation(1)],handelError(manageTaskController.deleteReminder));
export default tasksRouter;